version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  reviewers:
  - chinthakagodawita
