name: 'Auto Update'
description: 'A GitHub Action that auto-updates PRs with changes from their destination branch'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'git-pull-request'
  color: 'blue'
